const fs = require('fs');
const path = require('path');
require('dotenv').config();

const key = process.env.SHEETS_API_KEY ?? '';
if (!key) {
  console.warn('Warning: SHEETS_API_KEY is not set. Copy .env.example to .env and fill in the value.');
}

const output = `// Auto-generated by scripts/set-env.js — do not commit this file
export const sheetsApiKey = '${key}';
`;

fs.writeFileSync(path.join(__dirname, '../src/environments/secrets.ts'), output, 'utf-8');
